spring.application.name=taskmanager

spring.profiles.active=postgres
#spring.profiles.active=inmemory
#spring.profiles.active=h2

debug=true
server.port=8080
server.address=0.0.0.0
server.http2.enabled=true
spring.main.show-conditions=false

spring.cache.type=redis
spring.data.redis.host=0.0.0.0
spring.data.redis.port=6379

