spring.application.name=taskmanager

spring.profiles.active=postgres
#spring.profiles.active=inmemory
#spring.profiles.active=h2

debug=true
server.port=8080
server.address=0.0.0.0
server.http2.enabled=true
spring.main.show-conditions=false

#redis
spring.cache.type=redis
spring.data.redis.host=0.0.0.0
spring.data.redis.port=6379

#rabbitmq
spring.rabbitmq.host=0.0.0.0
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

